s = input("Enter your Name in Small Letters:\n")

s = s.replace('a','4',)
s = s.replace('b','8',)
s = s.replace('c','¢',)
s = s.replace('e','3',)
s = s.replace('g','9',)
s = s.replace('h','#',)
s = s.replace('i','!',)
s = s.replace('j','√',)
s = s.replace('o','0',)
s = s.replace('p','9',)
s = s.replace('r','®',)
s = s.replace('s','5',)
s = s.replace('t','7',)
s = s.replace('v','√',)
s = s.replace('y','¥',)
print(s)